apiVersion: v1
# Indicate this as a service
kind: Service
metadata:
  # Service name
  name: beauty-deployment
spec:
  selector:
      # Selector for Pods
    app: beauty
  ports:
      # Port Map
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
